language: java

script: mvn clean install -Dmaven.test.skip=true

compiler:
  -gcc
  
before_install:
  - sudo apt-get update
  
install:
  - sudo apt-get install python-dev python-numpy
  
before_script:
  

#deploy not working
deploy:
  provider: releases
  api_key: "BjsmCC9pnH8BsWTsDorM"
  file: "mipr-core-0.1-jar-with-dependencies.jar"
  skip_cleanup: true
  on:
    tags: true
