language: java
script: mvn clean install test
#compile test


#deploy not working
deploy:
  provider: releases
  api_key: "BjsmCC9pnH8BsWTsDorM"
  file: "mipr-core-0.1-jar-with-dependencies.jar"
  skip_cleanup: true
  on:
    tags: true
